sudo: required
dist: xenial

services:
  - mysql

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - php7.1-cli
      - php7.1-mysqli
      - php7.1-sqlite3
      - php7.1-mbstring

stages:
  - test
  # - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=4.0.0-rc.2
  
install:
  - npm i -g lix
  - npm install
  - lix install haxe $HAXE_VERSION
  - lix download

  
script:
  - lix run travix node
  - lix run travix neko
  - lix run travix run php7