sudo: required
dist: xenial

services:
  - mysql

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - php7.1-cli
      - php7.1-mysql
      - php7.1-sqlite3
      - php7.1-mbstring

stages:
  - test

language: node_js
node_js: 10

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - npm install
  - lix install haxe $HAXE_VERSION
  - lix download

  
script:
  - lix run travix node
  # - lix run travix neko
  - lix run travix php7