sudo: required
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

language: node_js
node_js: 6

os:
  - linux

before_install:
  - mysql --version
  - sudo apt-get install php-mysql
      
install:
  - yarn

script:
  - yarn travix node
  - yarn travix php

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/haxe